apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80            # Port your service is exposed on internally
      targetPort: 80      # Port your app listens on inside the container
      nodePort: 30080     # Port exposed on the node (between 30000–32767)

